on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT2 }}
          project-location: ${{ github.actor }}
          project-number: 1
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          column-name: Backlog